import { Amplify } from 'aws-amplify';
import type { NextPage } from 'next';
import Head from 'next/head';
import { Container, Modal, Navbar, SoundList } from '../components';
import { cognito } from '../utils/aws-exports';

Amplify.configure({ ...cognito });

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navbar />
      <main>
        <Modal />
        <Container>
          <SoundList />
        </Container>
      </main>
    </div>
  );
};

export default Home;
